name: Custom Issue
description: Describe your issue here.
title: "[Other]: "
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please describe your issue.
    validations:
      required: true
